<div class="entry-edit">
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo$this->__('Purchase Order List')?></h3></td>
            <td align="right">
                <button onclick="document.location.href='<?php echo $this->getNewUrl()?>'" class="scalable save" type="button"><span><?php echo $this->__('New')?></span></button>
                <!--<button onclick="document.getElementById('edit_form').submit();" class="scalable save" type="button"><span><?php echo $this->__('New')?></span></button>-->
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getGridParentHtml() ?>
</div>
<form id="edit_form" name="edit_form" action="<?php echo $this->getUrl('*/*/create')?>">
</form>
